mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sgfood.urls'))
]

sgfood/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views as sgfood_view

urlpatterns = [
    path('', sgfood_view.home, name='home'),
    path('register/', sgfood_view.register, name='register'),
    path('login/', auth_view.LoginView.as_view(template_name='sgfood/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='sgfood/logout.html'), name='logout'),
    path('category/', sgfood_view.category, name='category'),
    path('category/<category_id>/',
         sgfood_view.restaurant_list, name='restaurant_list'),
    path('category/<category_id>/restaurant/<restaurant_id>/',
         sgfood_view.restaurant_detail, name='restaurant_detail'),
    path('like_review', sgfood_view.like_review, name='like_review'),
    path('like_comment', sgfood_view.like_comment, name='like_comment'),
    path("review_create", sgfood_view.review_create, name="review_create"),
    path("comment_create", sgfood_view.comment_create, name="comment_create"),
    path("restaurant_rate", sgfood_view.restaurant_rate, name="restaurant_rate"),
]

sgfood/models.py
from django.db import models
from django.contrib.auth.models import User


string_format_2 = '{0} - {1}'
string_format_3 = '{0} - {1} - {2}'


class Category(models.Model):
    description = models.CharField(max_length=255)

    def __str__(self):
        return string_format_2.format(self.id, self.description)


class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    address = models.CharField(max_length=50)

    # many restaurants to one category
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return string_format_3.format(self.id, self.name, self.category)


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)

    rate = models.IntegerField(default=0)
    description = models.CharField(max_length=255)

    def get_comments(self):
        return self.comment_set.filter(reply=None)

    def __str__(self):
        return string_format_3.format(self.restaurant, self.description, self.user)


class LikeForReview(models.Model):
    # similar to composite primary key
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


# Note: one user can leave comment on one review many times
class Comment(models.Model):
    # many comments to one review
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    # many comments to one user
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    description = models.CharField(max_length=255)

    reply = models.ForeignKey('Comment', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return string_format_3.format(self.review, self.description, self.user)


class LikeForComment(models.Model):
    # similar to composite primary key
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

sgfood/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(
        max_length=20, label='First Name', required=False)
    last_name = forms.CharField(
        max_length=20, label='Last Name', required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']

sgfood/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse, Http404
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegisterForm
from .models import Category, Restaurant, Review, LikeForReview, Comment, LikeForComment


def home(request):
    context = {'home': 'home1'}
    return render(request, 'sgfood/home.html', context)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            msg = 'Create '+username+' account successfully'
            messages.success(request, msg)

            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request, 'sgfood/register.html', {'form': form})


def category(request):
    categories = Category.objects.all()
    return render(request, 'sgfood/category.html', {'categories': categories})


def restaurant_list(request, category_id):
    restaurants = Restaurant.objects.filter(category=category_id)

    context = {
        'restaurants': restaurants,
    }

    return render(request, 'sgfood/restaurant_list.html', context)


def restaurant_detail(request, category_id, restaurant_id):
    restaurant = Restaurant.objects.get(id=restaurant_id)
    reviews = Review.objects.filter(restaurant=restaurant).order_by("-pk")

    avg_rate = average_rating(reviews)

    context = {
        'restaurant': restaurant,
        'reviews': reviews,
        'avg_rate': avg_rate,
    }

    return render(request, 'sgfood/restaurant_detail.html', context)


def average_rating(reviews):
    avg_rating = 0
    if reviews.count() > 0:
        total = 0
        for review in reviews:
            total += review.rate
        avg_rating = total/reviews.count()
        return "{0:.2f}".format(avg_rating)
    else:
        return avg_rating


@login_required
def like_review(request):
    review_id = request.GET.get('review_id')
    preference = request.GET.get('preference')

    # [0]: unlike [1]:like
    if preference == "0":
        LikeForReview.objects.filter(
            review_id=review_id, user=request.user).delete()
        count = LikeForReview.objects.filter(review_id=review_id).count()
        return JsonResponse({'count': count, }, status=200)
    elif preference == "1":

        bExist = LikeForReview.objects.filter(
            review_id=review_id, user=request.user).exists()

        if not bExist:
            lr1 = LikeForReview(review_id=review_id, user=request.user)
            lr1.save()
            count = LikeForReview.objects.filter(review_id=review_id).count()
            response = JsonResponse({
                'status': 'succeeded ',
                'message': lr1.id,
                'count': count,
            }, status=200)
            return response

    response = JsonResponse({
        'status': 'failed',
        'message': 'LikeForReview sqlite exception',
    }, status=500)
    return response


@login_required
def like_comment(request):
    comment_id = request.GET.get('comment_id')
    preference = request.GET.get('preference')
    user = request.user

    # preference [0]:Unlike [1]:like
    if preference == "0":
        LikeForComment.objects.filter(
            comment_id=comment_id, user=user).delete()
        count = LikeForComment.objects.filter(comment_id=comment_id).count()

        return JsonResponse({'count': count, }, status=200)

    elif preference == "1":
        bExist = LikeForComment.objects.filter(
            comment_id=comment_id, user=user).exists()

        if not bExist:
            lc1 = LikeForComment(comment_id=comment_id, user=user)
            lc1.save()
            count = LikeForComment.objects.filter(
                comment_id=comment_id).count()

            response = JsonResponse({
                'status': 'succeeded',
                'message': lc1.id,
                'count': count,
            }, status=200)
            return response

    response = JsonResponse({
        'status': 'failed',
        'message': '',
    }, status=500)
    return response


def review_create(request):
    if request.user.is_authenticated:
        restaurant_id = request.GET.get("restaurant_id")
        description = request.GET.get("description")
        rate = request.GET.get("rate")

        review = Review(
            user=request.user,
            restaurant_id=restaurant_id,
            rate=int(rate),
            description=description
        )
        review.save()

        reviews = Review.objects.filter(
            restaurant_id=restaurant_id).order_by("-pk")

        content = {
            "reviews": reviews
        }

        return render(request, "sgfood/review.html", content)

        # return JsonResponse({"review_id": review.id}, status=200)
    else:
        return JsonResponse({"is_not_authenticated": True}, status=200)


def comment_create(request):
    if request.user.is_authenticated:
        review_id = request.GET.get("review_id")
        comment_id = request.GET.get("comment_id")
        description = request.GET.get("description")

        review = Review.objects.filter(id=review_id).first()

        if comment_id is not "":
            comment = Comment.objects.filter(id=comment_id).first()
        else:
            comment = None
        if review is not None:
            comment = Comment(
                user=request.user,
                review=review,
                description=description,
                reply=comment,
            )
            comment.save()

            restaurant = review.restaurant
            reviews = Review.objects.filter(
                restaurant=restaurant).order_by("-pk")
            content = {
                'reviews': reviews
            }
            return render(request, "sgfood/review.html", content)
        else:
            raise Http404("review id is not valid")
    else:
        return JsonResponse({"is_not_authenticated": True}, status=200)


def restaurant_rate(request):
    restaurant_id = request.GET.get('restaurant_id')

    reviews = Review.objects.filter(restaurant_id=restaurant_id)
    avg_rate = average_rating(reviews)
    review_count = reviews.count()

    response = JsonResponse({
        'review_count': review_count,
        'avg_rate': avg_rate,
    }, status=200)

    return response

sgfood/templates/sgfood/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <script src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'sgfood/style/style.css' %}">

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <!-- Brand/logo -->
        <div class="navbar-brand">
            <img src="{% static 'sgfood/icon/merlion-logo.png' %}" alt="logo" style="width:65px;">
        </div>

        <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                <!-- Links -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'category' %}">Category</a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- Links -->
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout- {{user.username}}</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% endif %}
        </ul>
    </nav>

    <title>{% block title %} Singapore Food Guide {% endblock %}</title>
</head>


<body>
    <div class="my-container">
        <div class="transparent-content">
            {% if messages %}
            {% for message in messages %}
            <div class="alert">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>
    </div>

    {% block javascript %}
    {% endblock javascript %}

</body>

</html>

sgfood/templates/sgfood/category.html
{% extends "sgfood/base.html" %}
{% load static %}
{% block title %} Category {% endblock %}
{% block content %}

<div class="container-fluid">
    <h2 class="mt-2 mb-3">Cuisine Category</h2>
    <div class="row">
        {% for c in categories %}
        <div class="col-lg-4 col-md-4 col-sm-6">
            <div class="cuisine-grid">
                <div class="cuisine-image">
                    <a href="{% url 'restaurant_list' c.id %}">
                        <img src="{% static 'sgfood/icon/' %}{{c.description}}.jpg" alt="cuisine image"
                            class="img-thumbnail">
                    </a>
                </div>
                <div class="cuisine-content mt-1 mb-3">
                    <h4 class="text-center">{{ c.description }}</h4>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

sgfood/templates/sgfood/home.html
{% extends "sgfood/base.html" %}
{% load static %}
{% block title %} Home {% endblock %}
<div class="bg"></div>

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-md-center">
        <div class="col-sm-12">
            <h1>Singapore Food Guide</h1>
            <p>Welcome to our Django Home Page</p>
        </div>
    </div>
</div>

{% endblock content %}

sgfood/templates/sgfood/login.html
{% extends "sgfood/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Login {% endblock %}
{% block content %}

<div class="container-fluid">
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <h1>
                Login
            </h1>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}

                <button class="btn btn-outline-info" type="submit">Log In</button>
            </form>
        </div>
    </div>

</div>

{% endblock content %}

sgfood/templates/sgfood/logout.html
{% extends "sgfood/base.html" %}
{% block title %} Logout {% endblock %}
{% block content %}

<div class="container">
    <h1>Log out successfully</h1>
</div>

{% endblock content %}

sgfood/templates/sgfood/register.html
{% extends "sgfood/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Sign up {% endblock %}
{% block content %}

<div class="container-fluid">
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <h1>Register</h1>

            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}

                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

sgfood/templates/sgfood/review.html
{% load app_tags %}
{% load static %}

<div class="col-md-6 my-review-comment-div">
    <ul id="ul-review" class="list-group list-group-flush">
        {% for review in reviews %}
        <li class="list-group-item">
            <blockquote class="blockquote">
                <p class="mb-0 p-large"><cite class="italic-gray-cite">{{review.user.username}}</cite></p>
                <p class="mb-0 p-large">{{review.description}}</p>
                <div class="my-test-div" data-single-review-star="{{review.rate}}">
                    <span id="single-review-span-star-1" class="fa fa-star-o unchecked" data-star-id="1"></span>
                    <span id="single-review-span-star-2" class="fa fa-star-o unchecked" data-star-id="2"></span>
                    <span id="single-review-span-star-3" class="fa fa-star-o unchecked" data-star-id="3"></span>
                    <span id="single-review-span-star-4" class="fa fa-star-o unchecked" data-star-id="4"></span>
                    <span id="single-review-span-star-5" class="fa fa-star-o unchecked" data-star-id="5"></span>
                </div>
                <footer class="p-large">
                    <button class="btn btn-sm btn-borderless btn-sg-show-comment-content">
                        <i class="far fa-comment-dots"></i>
                        <span>{{review.comment_set.count}} View</span>
                    </button>
                    {% if user.is_authenticated %}
                    <button class="btn btn-sm btn-borderless btn-sg-show-comment-textbox"
                        data-textbox-id="comment-for-review-{{review.id}}">
                        <i class="fa fa-reply"></i>
                        <span>Comment</span>
                    </button>
                    {% if review|query_review_like:user %}
                    <button class="btn btn-sm btn-sg-Review btn-borderless" data-review-id="{{review.id}}"
                        data-preference="0" type="button">
                        <i class="fa fa-heart heart-red"></i>
                        <span>Like</span>
                    </button>
                    {% else  %}
                    <button class="btn btn-sm btn-sg-Review btn-borderless" data-review-id="{{review.id}}"
                        data-preference="1" type="button">
                        <i class="fa fa-heart heart-gray"></i>
                        <span>Like</span>
                    </button>
                    {% endif  %}
                    {% endif %}
                    <span class="btn-sm btn-borderless" disabled>{{review.likeforreview_set.count}} people found
                        this review helpful</span>
                </footer>

                <div class="replied-comments container pl-5 d-display-none">
                    {% for comment in review.get_comments %}
                    <p class=" mb-0 p-mid"><cite class="italic-gray-cite">{{comment.user.username}}</cite></p>
                    <p class="mb-0 p-mid">{{comment.description}}</p>
                    <footer class="italic-gray-footer p-mid">
                        <button class="btn btn-sm btn-borderless btn-sg-show-reply-content">
                            <i class="far fa-comment-dots"></i>
                            <span>{{comment.comment_set.count}} View</span>
                        </button>
                        {% if user.is_authenticated %}
                        <button class="btn btn-sm btn-borderless btn-sg-show-reply-textbox"
                            data-textbox-id="reply-for-comment-{{comment.id}}">
                            <i class="fa fa-reply"></i>
                            <span>Reply</span>
                        </button>
                        {% if comment|query_comment_like:user %}
                        <button class="btn btn-sm btn-sg-Comment btn-borderless" data-comment-id="{{comment.id}}"
                            data-comment-preference="0" type="button">
                            <i class="fa fa-heart heart-red"></i>
                            <span>Like</span>
                        </button>
                        {% else %}
                        <button class="btn btn-sm btn-sg-Comment btn-borderless" data-comment-id="{{comment.id}}"
                            data-comment-preference="1" type="button">
                            <i class="fa fa-heart heart-gray"></i>
                            <span>Like</span>
                        </button>
                        {% endif %}
                        {% endif %}
                    </footer>

                    <div class="replied-comments container pl-5 d-display-none">
                        {% for reply in comment.comment_set.all %}
                        <p class="mb-0 p-small"><cite class="italic-gray-cite">{{reply.user.username}}</cite></p>
                        <p class="mb-0 p-small">{{reply.description}}</p>

                        {% endfor %}
                    </div>
                    <input id="reply-for-comment-{{comment.id}}"
                        class="form-control input-sm text-box-comment d-display-none"
                        data-textbox-review-id="{{review.id}}" data-textbox-comment-id="{{comment.id}}"
                        placeholder="default reply" type="text">
                    <br />
                    {% endfor%}
                </div>
                <input id="comment-for-review-{{review.id}}"
                    class="form-control input-sm text-box-comment d-display-none" data-textbox-review-id="{{review.id}}"
                    placeholder="default comment" type="text">
            </blockquote>
        </li>
        {% endfor %}
    </ul>
</div>


<script>
    $(".text-box-comment").keypress(function (event) {
        let keycode = (event.keyCode ? event.keyCode : event.which);
        let self = $(this);
        let description = $(this).val();
        let review_id = $(this).attr("data-textbox-review-id");
        let comment_id = $(this).attr("data-textbox-comment-id");

        if (comment_id == undefined) {
            comment_id = "";
        }

        // when press enter key
        if (keycode == '13') {
            $.ajax({
                type: "GET",
                url: "{% url 'comment_create' %}",
                // dataType: "json",
                data: {
                    "review_id": review_id,
                    "comment_id": comment_id,
                    "description": description,
                },
                success: function (data) {
                    if (data.is_not_authenticated) {
                        window.location.href = "{% url 'login' %}";
                    } else {
                        // refresh the div
                        $(".my-review-comment-div").parent().html(data);
                        // clear the content
                        self.val("");

                        let tempDiv = self.parent().children(".replied-comments");
                        tempDiv.toggle();
                    }
                },
                error: function (jqXHR, status) {
                    console.log(jqXHR)
                },
            });
        }
    });

    $(".btn-sg-Review").click(function () {
        let review_id = $(this).attr("data-review-id").toString();
        // [0]: unlike [1]:like
        let review_preference = $(this).attr("data-preference").toString();

        // keep the pointer of button object
        let self = $(this);
        let red = "heart-red";
        let gray = "heart-gray";

        // communicate with server
        $.ajax({
            url: '{% url "like_review" %}',
            type: 'GET',
            data: {
                'review_id': review_id,
                'preference': review_preference,
            },
            // dataType: 'json',
            success: function (data) {

                if (data.is_not_authenticated) {
                    window.location.href = "{% url 'login' %}";
                } else {
                    // $("#my-review-div").html(data);
                    // self.val("");
                    let count = data.count;
                    let display_content = `${count} people found this review helpful`;

                    console.log(this);
                    if (review_preference == "0") {
                        self.attr("data-preference", "1");
                        self.children("i").removeClass(red).addClass(gray);
                        self.parent().children("span").text(display_content);
                    } else if (review_preference == "1") {
                        self.attr("data-preference", "0");
                        self.children("i").removeClass(gray).addClass(red);
                        self.parent().children("span").text(display_content);
                    }
                    console.log(self);
                }
            },
            error: function (jqXHR, textStatus) {
                console.log(jqXHR);
                console.log('something wrong');
            },
        });
    });

    $(".btn-sg-Comment").click(function () {
        let comment_id = $(this).attr("data-comment-id").toString();
        let comment_preference = $(this).attr("data-comment-preference").toString();

        // keep the pointer of button object
        let self = $(this);
        let red = "heart-red";
        let gray = "heart-gray";

        $.ajax({
            type: "GET",
            dataType: "json",
            url: "{% url 'like_comment' %}",
            data: {
                "comment_id": comment_id,
                "preference": comment_preference,
            },
            success: function (data) {
                console.log(this);
                if (comment_preference == "0") {
                    self.attr("data-comment-preference", "1");
                    self.children('i').removeClass(red).addClass(gray);
                } else if (comment_preference == "1") {
                    self.attr("data-comment-preference", "0");
                    self.children('i').removeClass(gray).addClass(red);
                }
                console.log(self);
            },
            error: function (jqXHR, textStatus) {
                console.log(jqXHR);
            },
        });
    });

    $(document).ready(function () {
        $("div.my-test-div").each((idx, elem) => {
            let rate = parseInt(elem.getAttribute("data-single-review-star"));

            let arr = [];
            arr.push($(elem).children("#single-review-span-star-1"));
            arr.push($(elem).children("#single-review-span-star-2"));
            arr.push($(elem).children("#single-review-span-star-3"));
            arr.push($(elem).children("#single-review-span-star-4"));
            arr.push($(elem).children("#single-review-span-star-5"));

            let i = 0;
            for (i = 0; i < arr.length; i++) {
                if (i < rate) {
                    arr[i].removeClass("unchecked").addClass("checked");
                    arr[i].removeClass("fa-star-o").addClass("fa-star");
                } else {
                    arr[i].removeClass("checked").addClass("unchecked");
                    arr[i].removeClass("fa-star").addClass("fa-star-o");
                }
            }
        });
    });

    $(".btn-sg-show-comment-textbox").click(function () {
        console.log($(this));

        let textbox_id = $(this).attr("data-textbox-id");
        $("#" + textbox_id).toggle().focus();

    });

    $(".btn-sg-show-reply-textbox").click(function () {
        console.log($(this));
        let textbox_id = $(this).attr("data-textbox-id");
        console.log(textbox_id);
        $("#" + textbox_id).toggle().focus();
    });

    $(".btn-sg-show-comment-content").click(function () {
        $(this).parent().parent().children('.replied-comments').toggle();
    });

    $(".btn-sg-show-reply-content").click(function () {
        $(this).parent().parent().children('.replied-comments').toggle();
    });
</script>